### ISSUE TITLE
Credentials exposed to the world.

### ISSUE THREAD

**Issue by ecarrizo2** [ktsyr1/student-in-courses#5]
https://github.com/ktsyr1/student-in-courses/blob/f3088b02171efd22af828dad785a54e1ce29df18/texting.md?plain=1#L9

Your credentials are exposed to the world.

**Comment by AiQotayba** [comment]
Thanks for the warning 😍
It expired 3 days ago
Which means it is no longer a problem

**Comment by AiQotayba** [comment]
If there are other tips, you are welcome 😍
If not, can we close the issues?
